{% set version="1.0.1" %}
package:
  name: wisecondorx
  version:  {{ version }}

source:
  url: https://github.com/CenterForMedicalGeneticsGhent/wisecondorX/archive/v{{ version }}.tar.gz
  sha256: 86f9211f08c85ce10a630e121c66a819397383e1807a2bb0870761fa1a60c27b

build:
  number: 0
  noarch: python #

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pysam
    - futures
    - scipy
    - scikit-learn
    - numpy
    - r-jsonlite >=1.5
    - r-png
    - bioconductor-dnacopy

test:
  imports:
    - wisecondorX
  commands:
    - WisecondorX --help
    - WisecondorX convert --help
    - WisecondorX gender --help
    - WisecondorX newref --help
    - WisecondorX predict --help
about:
  home: https://github.com/CenterForMedicalGeneticsGhent/wisecondorX
  license: Attribution-NonCommercial-ShareAlike CC BY-NC-SA
  summary: 'WIthin-SamplE COpy Number aberration DetectOR, including sex chromosomes'
