{% set version = "2.0.0" %}

package:
  name: moff
  version: {{ version }}

source:
  url: https://github.com/compomics/moFF/archive/{{ version }}.tar.gz
  md5: 54d8a94b9a688f40c3c249beadf2f006

build:
  number: 1
  skip: True # [py27]

requirements:
  host:
    - python
    - pandas >=0.23.*
    - numpy >=1.15.*
    - argparse >1.2.1
    - scipy >=1.1.*
    - scikit-learn >=0.19
    - pymzml >=2.0.3
    - mono
    - simplejson >=3.16.1
    - brain-isotopic-distribution
    - pyteomics >=3.5

  run:
    - python
    - pandas >=0.23.*
    - numpy >=1.15.*
    - argparse >1.2.1
    - scipy >=1.1.*
    - scikit-learn >0.19
    - pymzml >=2.0.3
    - mono
    - simplejson >=3.16.1
    - brain-isotopic-distribution 
    - pyteomics >=3.5

test:
  commands:
    - 'moff_all.py -h'

about:
  home: https://github.com/compomics/moFF
  license: Apache 2.0
  license_file: license
  summary: moFF is an OS independent tool designed to extract apex MS1 intensity using a set of identified MS2 peptides.
